name: Build

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        java: [ '16.0' ]
        scala: [ '3.0.0' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - name: Cache SBT
        uses: coursier/cache-action@v6
        with:
          extraKey: scala-${{ matrix.scala }}
      - name: check compile
        run: sbt compile
  test:
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        java: [ '16.0' ]
        scala: [ '3.0.0' ]
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - name: Cache SBT
        uses: coursier/cache-action@v6
        with:
          extraKey: scala-${{ matrix.scala }}
      - name: check compile
        run: sbt test
